## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to group (i.e. any columns left out will become part of the same group)
mergeBy: ['Project', 'Cell_Type', 'Genotype', 'Time', 'Bio_Rep', 'Tech_Rep']

## Genome-specific reference parameters
fasta: '/proj/seq/data/hg38_UCSC/Sequence/BWAIndex/genome.fa' 
chromSizes: '/proj/phanstiel_lab/software/resources/hg38_chromSizes.txt'